version: "3"

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  db:
    image: mysql:5.7
    container_name: app-db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
      - ./.docker/database/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=infrawebnovo
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=1
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    command: [ "php", "-d", "upload_max_filesize = 10G", "-d", "post_max_size = 10G", "-S", "[::]:8080", "-t", "/var/www/html" ]
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: hever
    ports:
      - 8080:8080

  web:
    image: nginx:stable
    container_name: app-nginx
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs:/var/log/nginx
    depends_on:
      - php
      - db
    ports:
      - "9090:80"
      - "443:8083"
    networks:
      - app-network

  redis:
    image: redis
    container_name: app-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network

  # QUEUE
  # queue:
  #   image: ambientum/php:7.1
  #   container_name: app-queue
  #   command: php artisan horizon
  #   volumes:
  #     - .:/var/www/app
  #   restart: unless-stopped
  #   links:
  #     - mysql
  #     - cache